### ISSUE TITLE
Intermediate config does not support IE 11 on Windows 7

### ISSUE THREAD

**Issue by amq** [mozilla/ssl-config-generator#51] opened 2019-08-09 07:31 UTC
How to reproduce:
- Use https://ssl-config.mozilla.org/#server=nginx&server-version=1.17.0&config=intermediate
- Run https://www.ssllabs.com/ssltest/

**Comment by tomato42** [comment] 2019-08-13 18:09
that shouldn't be the case, intermediate enables DHE-RSA-AES128-GCM-SHA256 and it's one of the ciphers supported by IE 11 on Win7

what kind of error you see reported by ssllabs?

**Comment by jrchamp** [comment] 2019-08-13 18:10
ECDSA certificates are recommended by the intermediate configuration. IE 11 on Windows 7 only supports ECDHE with AES-GCM when using ECDSA.

If you are using a free option like Let's Encrypt, please encourage them to enable ECDSA leaf certificates.

**Comment by april** [comment] 2019-08-13 21:20
Microsoft also lists this as a supported configuration:
https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-7

@naumanshah03, maybe you know?

**Comment by april** [comment] 2019-08-16 17:49
Closing this out as I'm pretty sure it's a bug in SSL Labs, not a bug in the generator.

**Closed by april** 2019-08-16 17:49 UTC
